# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.yurtski.com
title: YurtSki
email: info@yurtski.com
description: > # "Write an awesome description for your new site here. 
  YurtSki provides backcountry lodging to backcountry skiers and snowboarders in the Swan Mountains
  of Montana.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: http://instagram.com/yurtskimt
  - title: facebook
    url: http://facebook.com/yurtski